AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket
Parameters:
  AppPrefix:
    Description: 'prefix description'
    Type: String
    AllowedValues: [demo1, demo2]
    Default: demo1
    ConstraintDescription: 'select prefix'

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['',[!Ref AppPrefix , '-s3-demo-base']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: env
          Value: !Ref AppPrefix
Outputs:
  S3URL:
    Value: !Join ['',[!Ref AppPrefix, '-demo-S3']]
    Description: S3 url
                
                
     